// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "go.wilaris.de/provider-opentelekomcloud/apis/network/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PrivateZone.
func (mg *PrivateZone) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.VPCs); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCs[i3].VPCID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.VPCs[i3].VPCIDRef,
			Selector:     mg.Spec.ForProvider.VPCs[i3].VPCIDSelector,
			To: reference.To{
				List:    &v1alpha1.VPCList{},
				Managed: &v1alpha1.VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.VPCs[i3].VPCID")
		}
		mg.Spec.ForProvider.VPCs[i3].VPCID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.VPCs[i3].VPCIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RecordSet.
func (mg *RecordSet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PrivateZoneID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PrivateZoneIDRef,
		Selector:     mg.Spec.ForProvider.PrivateZoneIDSelector,
		To: reference.To{
			List:    &PrivateZoneList{},
			Managed: &PrivateZone{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateZoneID")
	}
	mg.Spec.ForProvider.PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PrivateZoneIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PublicZoneID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PublicZoneIDRef,
		Selector:     mg.Spec.ForProvider.PublicZoneIDSelector,
		To: reference.To{
			List:    &PublicZoneList{},
			Managed: &PublicZone{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PublicZoneID")
	}
	mg.Spec.ForProvider.PublicZoneID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PublicZoneIDRef = rsp.ResolvedReference

	return nil
}
